default-host: router

hosts:
  router:
    # directory containing the config files
    source: ./router/

    # info to connect to the server
    server:
      addr: 10.0.0.1
      user: root

    # arbitrary params that can be used on config files
    params:
      pppoe:
        username: john@doe.com
        password: 123abc
